apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: annoyed-mollusk-nodejs 
  janus-idp.io/tekton: annoyed-mollusk-nodejs
  backstage.io/kubernetes-id: annoyed-mollusk-nodejs
  backstage.io/kubernetes-namespace: rhtap-dmo 
  app.kubernetes.io/part-of: annoyed-mollusk-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  