apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: annoyed-mollusk-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: annoyed-mollusk-nodejs 
  name: annoyed-mollusk-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: annoyed-mollusk-nodejs 
